title: SLIDE
description: Official documentation of SLIDE software 4.
remote_theme: ElektrikAkar/jekyll-rtd-ox-theme

# Theme settings:
site_author: SLIDE authors
repo_url: "https://github.com/davidhowey/SLIDE/"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
